version: '3'
services:
  web-server:
    image: "assignment-server:latest"
    ports:
     - "5000:5000"
  redis:
    image: "redis:alpine"
    ports:
    - "6379:6379"
  postgresql:
    image: "postgres:alpine"
    ports:
    - "5432:5432"