version: '3'
services:
  web-server:
    networks:
    - backend
    image: assignment-server:latest
    ports:
     - 8080:8080
    depends_on:
    - redis
    - postgresql
    links:
    - redis
    - postgresql
  redis:
    networks:
    - backend
    volumes:
    - ./redisdata:/data
    image: redis:alpine
    ports:
    - 6379:6379
  postgresql:
    networks:
    - backend
    volumes:
    - ./pgdata:/var/lib/postgresql/data
    image: postgres:alpine
    ports:
    - 5432:5432

networks:
  backend:

volumes:
  postgre-data:
  redis-data: